version: "3"
services:
    db:
        image: postgres:14.0
        env_file:
            - .config
        ports:
            - "${POSTGRES_HOST_PORT}:5432"
        volumes:
            - "${POSTGRES_HOST_PATH}:${PGDATA}"