import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useConnect, useEagerConnect, useWeb3React } from "modules/wallet";
import Account from "components/Account";
import Chain from "components/Chain";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  useEagerConnect();
  // TODO handle error
  const { account, active } = useWeb3React();
  const login = useConnect();

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* TODO this should be part of a "nav" or "header" */}
        {active && account ? (
          <p>
            Hello <Account /> on <Chain />
          </p>
        ) : (
          <button onClick={login}>Login with metamask</button>
        )}

        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
