import type { NextPage } from "next";
import Head from "next/head";
import { useEagerConnect, useWeb3React } from "client/modules/wallet";
import Account from "components/Account";
import Chain from "components/Chain";

import styles from "../styles/Home.module.css";
import { useNfts } from "client/io/nfts";
import Avatar from "components/Avatar";
import AvatarSelector from "components/AvatarSelector";

const Profile: NextPage = () => {
  useEagerConnect();
  // TODO handle error
  const { account, active } = useWeb3React();
  const { data: nfts } = useNfts(account);

  // TODO abstract
  const avatarUrl = (() => {
    // Grab the first, but evenutally grab the chosen one
    const meta = nfts?.result?.find((element) => !!element.metadata);
    if (!meta) {
      return;
    }
    return JSON.parse(meta.metadata)?.image;
  })();

  if (!active || !account) {
    return <div>Please login</div>;
  }

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          Hello <Account /> on <Chain />
          <Avatar url={avatarUrl} />
        </div>

        <h1 className={styles.title}>Profile</h1>

        <AvatarSelector />
      </main>
    </div>
  );
};

export default Profile;
